FROM node:15

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y wget

RUN npm init -y

RUN npm install express --save

#ENV DOCKERIZE_VERSION v0.6.1
#RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
#    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
#    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

EXPOSE 3000

CMD ["bash"]

# Inicializacao : docker run --rm -it -v $(pwd)/:/usr/src/app -d -p 3000:3000 --name node node-express-app:latest node index.js